language: node_js
node_js:
  - "5.11"
before_install: npm install --global apigeetool
after_success:
    "apigeetool deploynodeapp -n test-apigee-travis -d . -m app.js -o rajamalw -e prod -b /mytravis -u $APIGEE_USERNAME -p $APIGEE_PASSWORD"